using System.Text;
using AIResourceCalculator.Models;

namespace AIResourceCalculator.Services;

public class ConfigExportService
{
    public string ExportTerraform(ResourceRequirement req, ProjectConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by AI Resource Calculator");
        sb.AppendLine($"# Project: {config.ProjectName}, Users: {config.UserCount}");
        sb.AppendLine();

        foreach (var infra in req.Infrastructure)
        {
            var name = infra.Name.ToLower().Replace(" ", "_").Replace("(", "").Replace(")", "");
            sb.AppendLine($"resource \"aws_instance\" \"{name}\" {{");
            sb.AppendLine($"  count         = {infra.NodeCount}");
            sb.AppendLine($"  ami           = \"ami-0c55b159cbfafe1f0\"");
            sb.AppendLine($"  instance_type = \"{GetInstanceType(infra.Cpu, infra.RamGb)}\"");
            sb.AppendLine();
            sb.AppendLine("  tags = {");
            sb.AppendLine($"    Name        = \"{config.ProjectName}-{name}\"");
            sb.AppendLine($"    Environment = \"production\"");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (config.DeploymentType == DeploymentType.Kubernetes)
        {
            sb.AppendLine("# Kubernetes cluster definition");
            sb.AppendLine($"resource \"aws_eks_cluster\" \"{config.ProjectName.ToLower().Replace(" ", "_")}\" {{");
            sb.AppendLine($"  name     = \"{config.ProjectName}\"");
            sb.AppendLine($"  role_arn = aws_iam_role.eks.arn");
            sb.AppendLine();
            sb.AppendLine("  vpc_config {");
            sb.AppendLine("    subnet_ids = aws_subnet.public[*].id");
            sb.AppendLine("  }");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    public string ExportAnsible(ResourceRequirement req, ProjectConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by AI Resource Calculator");
        sb.AppendLine($"# Project: {config.ProjectName}");
        sb.AppendLine("---");
        sb.AppendLine($"- name: Deploy {config.ProjectName} infrastructure");
        sb.AppendLine("  hosts: all");
        sb.AppendLine("  become: yes");
        sb.AppendLine("  vars:");
        sb.AppendLine($"    project_name: {config.ProjectName}");
        sb.AppendLine($"    user_count: {config.UserCount}");
        sb.AppendLine($"    deployment_type: {config.DeploymentType}");
        sb.AppendLine();
        sb.AppendLine("  tasks:");

        foreach (var infra in req.Infrastructure)
        {
            sb.AppendLine($"    - name: Configure {infra.Name}");
            sb.AppendLine("      ansible.builtin.include_role:");
            sb.AppendLine($"        name: \"setup_{infra.Name.ToLower().Replace(" ", "_")}\"");
            sb.AppendLine("      vars:");
            sb.AppendLine($"        cpu_cores: {infra.Cpu}");
            sb.AppendLine($"        ram_gb: {infra.RamGb}");
            sb.AppendLine($"        instance_count: {infra.NodeCount}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    public string ExportHld(ResourceRequirement req, ProjectConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# High-Level Design Document");
        sb.AppendLine($"# Project: {config.ProjectName}");
        sb.AppendLine();
        sb.AppendLine("## 1. Project Overview");
        sb.AppendLine($"- **Project**: {config.ProjectName}");
        sb.AppendLine($"- **Expected Users**: {config.UserCount}");
        sb.AppendLine($"- **Deployment Type**: {config.DeploymentType}");
        sb.AppendLine($"- **Load Profile**: {config.LoadProfile}");
        sb.AppendLine($"- **HA Enabled**: {config.DeploymentType}");
        sb.AppendLine();
        sb.AppendLine("## 2. Resource Requirements");
        sb.AppendLine($"| Resource | Required |");
        sb.AppendLine($"|----------|----------|");
        sb.AppendLine($"| vCPU     | {req.TotalCpu:F1} cores |");
        sb.AppendLine($"| RAM      | {req.TotalRamGb:F1} GB |");
        sb.AppendLine($"| Storage  | {req.TotalStorageGb} GB |");
        sb.AppendLine($"| IOPS     | {req.TotalIops} |");
        sb.AppendLine();
        sb.AppendLine("## 3. Infrastructure");
        sb.AppendLine("| Node Type | Count | vCPU | RAM (GB) | Storage (GB) |");
        sb.AppendLine("|-----------|-------|------|----------|--------------|");

        foreach (var infra in req.Infrastructure)
        {
            sb.AppendLine($"| {infra.Name} | {infra.NodeCount} | {infra.Cpu} | {infra.RamGb} | {infra.StorageGb} |");
        }

        sb.AppendLine();
        sb.AppendLine("## 4. Components");

        foreach (var comp in req.Components)
        {
            if (!string.IsNullOrEmpty(comp.Category))
                sb.AppendLine($"### {comp.Category}");
            sb.AppendLine($"- **{comp.Name}**: CPU={comp.Cpu}, RAM={comp.RamGb}GB, Replicas={comp.Replicas}");
        }

        sb.AppendLine();
        sb.AppendLine("## 5. Compliance Validation");

        return sb.ToString();
    }

    public string ExportPdf(ResourceRequirement req, ProjectConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html><html><head><meta charset='UTF-8'>");
        sb.AppendLine("<style>body{font-family:Arial;margin:40px}h1{color:#2c3e50}table{border-collapse:collapse;width:100%;margin:15px 0}th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#3498db;color:white}.kpi{display:flex;gap:15px}.kpi-box{background:#2980b9;color:white;padding:15px;border-radius:6px;flex:1}</style>");
        sb.AppendLine("</head><body>");
        sb.AppendLine($"<h1>{config.ProjectName} - Resource Report</h1>");
        sb.AppendLine($"<p>Users: {config.UserCount} | Deployment: {config.DeploymentType} | Profile: {config.LoadProfile} | HA: {config.DeploymentType}</p>");
        sb.AppendLine("<div class='kpi'>");
        sb.AppendLine($"<div class='kpi-box'><h3>vCPU</h3><p>{req.TotalCpu:F1}</p></div>");
        sb.AppendLine($"<div class='kpi-box'><h3>RAM</h3><p>{req.TotalRamGb:F1} GB</p></div>");
        sb.AppendLine($"<div class='kpi-box'><h3>Storage</h3><p>{req.TotalStorageGb} GB</p></div>");
        sb.AppendLine($"<div class='kpi-box'><h3>IOPS</h3><p>{req.TotalIops}</p></div>");
        sb.AppendLine("</div>");
        sb.AppendLine("<h2>Infrastructure</h2><table><tr><th>Node</th><th>vCPU</th><th>RAM</th><th>Count</th><th>Storage</th></tr>");
        foreach (var i in req.Infrastructure)
            sb.AppendLine($"<tr><td>{i.Name}</td><td>{i.Cpu}</td><td>{i.RamGb}</td><td>{i.NodeCount}</td><td>{i.StorageGb} GB</td></tr>");
        sb.AppendLine("</table>");
        sb.AppendLine("<h2>Components</h2><table><tr><th>Name</th><th>vCPU</th><th>RAM</th><th>Replicas</th></tr>");
        foreach (var c in req.Components.Where(c => c.Cpu > 0))
            sb.AppendLine($"<tr><td>{c.Name}</td><td>{c.Cpu:F1}</td><td>{c.RamGb:F1}</td><td>{c.Replicas}</td></tr>");
        sb.AppendLine("</table></body></html>");
        return sb.ToString();
    }

    public string ExportTxt(ResourceRequirement req, ProjectConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("========================================");
        sb.AppendLine($"  {config.ProjectName} - Resource Report");
        sb.AppendLine("========================================");
        sb.AppendLine($"  Users:       {config.UserCount}");
        sb.AppendLine($"  Deployment:  {config.DeploymentType}");
        sb.AppendLine($"  Profile:     {config.LoadProfile}");
        sb.AppendLine($"  HA:          {config.DeploymentType}");
        sb.AppendLine("----------------------------------------");
        sb.AppendLine($"  vCPU:        {req.TotalCpu:F1} cores");
        sb.AppendLine($"  RAM:         {req.TotalRamGb:F1} GB");
        sb.AppendLine($"  Storage:     {req.TotalStorageGb} GB");
        sb.AppendLine($"  IOPS:        {req.TotalIops}");
        sb.AppendLine("----------------------------------------");
        sb.AppendLine("  Infrastructure:");
        foreach (var i in req.Infrastructure)
            sb.AppendLine($"    {i.Name}: {i.NodeCount}x ({i.Cpu} vCPU, {i.RamGb} GB, {i.StorageGb} GB)");
        sb.AppendLine("----------------------------------------");
        sb.AppendLine("  Components:");
        foreach (var c in req.Components.Where(c => c.Cpu > 0))
            sb.AppendLine($"    {c.Name}: {c.Cpu:F1} vCPU, {c.RamGb:F1} GB, {c.Replicas} replicas");
        sb.AppendLine("========================================");
        return sb.ToString();
    }

    public string ExportMermaid(ResourceRequirement req, ProjectConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("```mermaid");
        sb.AppendLine("graph TD");
        if (config.DeploymentType == DeploymentType.Kubernetes || config.DeploymentType == DeploymentType.Hybrid)
        {
            var lb = "LB[Load Balancer]";
            var masters = string.Join(" & ", req.Infrastructure.Where(n => n.Name.Contains("Master")).Select(n => $"M{n.Name.Replace(" ", "")}[{n.Name}]"));
            var workers = string.Join(" & ", req.Infrastructure.Where(n => n.Name.Contains("Worker")).Select(n => $"W{n.Name.Replace(" ", "")}[{n.Name}]"));
            var sql = req.Infrastructure.FirstOrDefault(n => n.Name.Contains("SQL"));
            var sqlNode = sql != null ? $"SQL[{sql.Name}]" : "SQL[SQL Server]";
            sb.AppendLine($"  {lb} --> {masters}");
            sb.AppendLine($"  {masters} --> {workers}");
            sb.AppendLine($"  {workers} --> {sqlNode}");
        }
        else
        {
            var sql = req.Infrastructure.FirstOrDefault(n => n.Name.Contains("SQL"));
            var app = req.Infrastructure.FirstOrDefault(n => n.Name.Contains("App"));
            var web = req.Infrastructure.FirstOrDefault(n => n.Name.Contains("Web"));
            if (sql != null) sb.AppendLine($"  SQL[SQL Server] --> APP[App Server]");
            if (app != null && web != null) sb.AppendLine($"  APP[App Server] --> WEB[{web.Name}]");
            if (sql != null && web == null) sb.AppendLine($"  SQL[SQL Server] --> APP[App Server]");
        }
        sb.AppendLine("```");
        return sb.ToString();
    }

    public string ExportSvg(ResourceRequirement req, ProjectConfig config)
    {
        var x = 50;
        var y = 50;
        var bw = 180;
        var bh = 60;
        var gap = 40;
        var w = 800;
        var h = 500;
        var sb = new StringBuilder();
        sb.AppendLine($"<svg xmlns='http://www.w3.org/2000/svg' width='{w}' height='{h}'>");
        sb.AppendLine($"<rect width='{w}' height='{h}' fill='#f5f6fa' rx='10'/>");
        sb.AppendLine($"<text x='20' y='30' font-size='20' font-weight='bold' fill='#2c3e50'>{config.ProjectName} - Infrastructure</text>");

        var nodes = req.Infrastructure.ToList();
        var cols = Math.Max(1, (int)Math.Ceiling(Math.Sqrt(nodes.Count)));

        for (int i = 0; i < nodes.Count; i++)
        {
            var cx = x + (i % cols) * (bw + gap);
            var cy = y + 60 + (i / cols) * (bh + gap);
            var n = nodes[i];
            var color = n.Name.Contains("SQL") ? "#e74c3c" : n.Name.Contains("Master") ? "#3498db" : n.Name.Contains("Worker") ? "#2ecc71" : n.Name.Contains("App") ? "#9b59b6" : "#f39c12";
            sb.AppendLine($"<rect x='{cx}' y='{cy}' width='{bw}' height='{bh}' rx='8' fill='{color}' opacity='0.9'/>");
            sb.AppendLine($"<text x='{cx + bw / 2}' y='{cy + 22}' text-anchor='middle' font-size='13' font-weight='bold' fill='white'>{n.Name}</text>");
            sb.AppendLine($"<text x='{cx + bw / 2}' y='{cy + 40}' text-anchor='middle' font-size='11' fill='white'>{n.Cpu} vCPU | {n.RamGb} GB | {n.NodeCount}x</text>");
        }

        for (int i = 1; i < nodes.Count; i++)
        {
            var px1 = x + (0 % cols) * (bw + gap) + bw / 2;
            var py1 = y + 60 + (0 / cols) * (bh + gap) + bh;
            var px2 = x + (i % cols) * (bw + gap) + bw / 2;
            var py2 = y + 60 + (i / cols) * (bh + gap);
            sb.AppendLine($"<line x1='{px1}' y1='{py1}' x2='{px2}' y2='{py2}' stroke='#95a5a6' stroke-width='2' stroke-dasharray='5,5'/>");
        }

        sb.AppendLine("</svg>");
        return sb.ToString();
    }

    private string GetInstanceType(double cpu, double ram)
    {
        return (cpu, ram) switch
        {
            (<= 2, <= 4) => "t3.medium",
            (<= 4, <= 16) => "t3.large",
            (<= 8, <= 32) => "m5.xlarge",
            (<= 16, <= 64) => "m5.2xlarge",
            (<= 32, <= 128) => "m5.4xlarge",
            (<= 64, <= 256) => "m5.8xlarge",
            _ => "m5.4xlarge"
        };
    }
}
